name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hello-app:latest
    - name: start the container
      run: docker run -d -p 8080:8080 --name simple_hello_app -it hello-app
    - name: test it
      run: docker ps -a | grep hello_app; curl http://localhost:8080
